DROP TRIGGER calculate_rating_lost_1;
DROP TRIGGER calculate_rating_lost_2;

DROP TRIGGER delete_rating_when_game_deleted;

DROP TRIGGER enable_resources_when_match_finished;

DROP TRIGGER disable_court_and_tournament_users_by_match_created;
DROP TRIGGER enable_court_and_tournament_users_by_match_deleted;