DELETE FROM rating;
DELETE FROM game;
DELETE FROM match;
DELETE FROM tournament_user;
DELETE FROM user_pic;
DELETE FROM user;
DELETE FROM court;
DELETE FROM tournament;
DELETE FROM unit;
DELETE FROM tournament_settings;
DELETE FROM defaults;
DELETE FROM city;
DELETE FROM region;
DELETE FROM state;

DELETE FROM `sqlite_sequence` WHERE `name` = 'rating';
DELETE FROM `sqlite_sequence` WHERE `name` = 'game';
DELETE FROM `sqlite_sequence` WHERE `name` = 'match';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament_user';
DELETE FROM `sqlite_sequence` WHERE `name` = 'user_pic';
DELETE FROM `sqlite_sequence` WHERE `name` = 'user';
DELETE FROM `sqlite_sequence` WHERE `name` = 'court';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament';
DELETE FROM `sqlite_sequence` WHERE `name` = 'unit';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament_settings;';
DELETE FROM `sqlite_sequence` WHERE `name` = 'defaults';
DELETE FROM `sqlite_sequence` WHERE `name` = 'city';
DELETE FROM `sqlite_sequence` WHERE `name` = 'region';
DELETE FROM `sqlite_sequence` WHERE `name` = 'state';
