DELETE FROM team_order_110;
DELETE FROM team_user;
DELETE FROM team;
DELETE FROM team_color;
DELETE FROM rating;
DELETE FROM game_type;
DELETE FROM game_110;
DELETE FROM game;
DELETE FROM match_110;
DELETE FROM "match";
DELETE FROM user_lab;
DELETE FROM user_pic;
DELETE FROM tournament_user;
DELETE FROM user;
DELETE FROM "group";
DELETE FROM court;
DELETE FROM tournament_settings;
DELETE FROM defaults;
DELETE FROM tournament_type;
DELETE FROM tournament;
DELETE FROM unit;
DELETE FROM city;
DELETE FROM region;
DELETE FROM state;

DELETE FROM `sqlite_sequence` WHERE `name` = 'team_order_110';
DELETE FROM `sqlite_sequence` WHERE `name` = 'team_user';
DELETE FROM `sqlite_sequence` WHERE `name` = 'team';
DELETE FROM `sqlite_sequence` WHERE `name` = 'team_color';
DELETE FROM `sqlite_sequence` WHERE `name` = 'rating';
DELETE FROM `sqlite_sequence` WHERE `name` = 'game_type';
DELETE FROM `sqlite_sequence` WHERE `name` = 'game_110';
DELETE FROM `sqlite_sequence` WHERE `name` = 'game';
DELETE FROM `sqlite_sequence` WHERE `name` = 'match_110';
DELETE FROM `sqlite_sequence` WHERE `name` = 'match';
DELETE FROM `sqlite_sequence` WHERE `name` = 'user_lab';
DELETE FROM `sqlite_sequence` WHERE `name` = 'user_pic';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament_user';
DELETE FROM `sqlite_sequence` WHERE `name` = 'user';
DELETE FROM `sqlite_sequence` WHERE `name` = 'group';
DELETE FROM `sqlite_sequence` WHERE `name` = 'court';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament_settings';
DELETE FROM `sqlite_sequence` WHERE `name` = 'defaults';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament_type';
DELETE FROM `sqlite_sequence` WHERE `name` = 'tournament';
DELETE FROM `sqlite_sequence` WHERE `name` = 'unit';
DELETE FROM `sqlite_sequence` WHERE `name` = 'city';
DELETE FROM `sqlite_sequence` WHERE `name` = 'region';
DELETE FROM `sqlite_sequence` WHERE `name` = 'state';